version: '3.8'

services:
  create:
    build:
      context: ./backend/create-person-service
    ports:
      - "5001:5001"
    environment:
      DB_URL: mysql+pymysql://root:1234@db/crud_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  read:
    build:
      context: ./backend/get-people-service
    ports:
      - "5002:5002"
    environment:
      DB_URL: mysql+pymysql://root:1234@db/crud_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  update:
    build:
      context: ./backend/update-person-service
    ports:
      - "5003:5003"
    environment:
      DB_URL: mysql+pymysql://root:1234@db/crud_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  delete:
    build:
      context: ./backend/delete-person-service
    ports:
      - "5004:5004"
    environment:
      DB_URL: mysql+pymysql://root:1234@db/crud_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  log:
    build:
      context: ./backend/get-logs-service
    ports:
      - "5005:5005"
    environment:
      DB_URL: mysql+pymysql://root:1234@db/crud_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: crud_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:


